# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib cosmxscan, .registration = TRUE
NULL

#' Streaming reader over a wide CosMx exprMat CSV (.csv or .csv.gz).
#'
#' `#[extendr]` is required on the STRUCT as well as on the impl block below.
#' Without it extendr generates no external-pointer conversions and the impl
#' fails to compile with "the trait bound `CosmxReader: ToVectorValue` is not
#' satisfied" -- it falls back to treating the struct as a value to coerce
#' into an R vector. See extendr-api's own altrep_tests.rs: "need to make the
#' object `.into_robj()`-able".
#'
#' @section Methods:
#'\subsection{Method `new`}{
#'Open a scanner. `.gz` is detected by extension and inflated inline.
#'}
#'
#'\subsection{Method `next_chunk`}{
#'Scan up to `max_rows` data rows, returning their nonzero triplets.
#'}
#'
#'\subsection{Method `close`}{
#'Release the file handle.
#'}
#'
#'\subsection{Method `rows_done`}{
#'Data rows consumed so far.
#'}
#'
CosmxReader <- new.env(parent = emptyenv())

CosmxReader$new <- function(path, skip_cols) .Call(wrap__CosmxReader__new, path, skip_cols)

CosmxReader$next_chunk <- function(max_rows) .Call(wrap__CosmxReader__next_chunk, self, max_rows)

CosmxReader$close <- function() .Call(wrap__CosmxReader__close, self)

CosmxReader$rows_done <- function() .Call(wrap__CosmxReader__rows_done, self)

#' @export
`$.CosmxReader` <- function (self, name) { func <- CosmxReader[[name]]; environment(func) <- environment(); func }

#' @export
`[[.CosmxReader` <- `$.CosmxReader`

# nolint end
